### ISSUE TITLE
'No UserPool' issue after Cognito install 

### ISSUE THREAD

**Issue by Canopix** [aws-samples/aws-serverless-airline-booking#10] opened 2019-05-08 00:19 UTC
I have an Issue after Cognito install, I made each change of episode 1 and when I tried to test the Sign-Up process, the legend aside of the button is "No userPool" 

Image: [https://i.imgur.com/muhPAFY.png](https://i.imgur.com/muhPAFY.png)

Any Idea?
Thanks in advance

**Comment by heitorlessa** [comment] 2019-05-10 14:50
Hey - Thanks for opening up the issue ;)

 It seems it's not being able to read the UserPool from the file `src/aws-exports.js`. You should see `aws_cognito_region`, `aws_user_pools_id,  and `aws_user_pools_web_client_id` as that's what Amplify would look.

 Can you share the steps to help me reproduce it?

 Thanks!

**Comment by heitorlessa** [comment] 2019-05-22 09:54
hey @Canopix I'm resolving this now but please reopen if you're still experiencing that - I couldn't reproduce it.

**Closed by heitorlessa** 2019-05-22 09:54 UTC
Labels: episode1
